spring.application.name=backend-java

spring.datasource.url=jdbc:postgresql://localhost:5432/todolist-db
spring.datasource.username=postgresql
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
