spring.application.name=backend-java

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spotify_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgresql}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}

spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=false

spring.profiles.active=dev